### PR TITLE
Imports organized and all output with log4j

### PR DESCRIPTION
**Pull request by angoca**
Imports were organized, and not using *.
Log4j v1 was moved to log4j v2
All system.out, system.err and printStackTrace were replaced by log4j
log_error, log_trace and log_info were removed and replaced by log4j
No logger as argument for init method
Comments in class as javadoc

### CODE REVIEW

**Comment by wieck** [comment]
Overall this looks good. 

One issue though. There was a reason why the TRACE level was emitted into a separate file. We use that during development of new application modules, especially for stored procedure implementations. When the properties file specifies **traceTerminalIO=true** the Monkey threads will output all the simulated terminal output. This way the developer can verify that the implementation correctly transports the necessary data from the simulated user terminal into the stored procedure **and back**. This is perhaps an abuse of the log system and we might need to use a different way of producing this output.

All the log levels need to be revised. There are a lot of ERROR and WARN messages that are in fact INFO. But we can adjust that after merging.

**Comment by angoca** [comment]
Ok, I got it. In this case, I am going to move jTPCCMonkey to another java package. In this way, this class will belong to another Logger, and this could have a different configuration in log4j. Then, I will remove the traceTerminalIO because this will be configured independently via log4j (With another Appender), and not inside the code.

**Comment by wieck** [comment]
On 4/7/21 9:39 AM, Andres Gomez Casanova wrote:
> Ok, I got it. In this case, I am going to move jTPCCMonkey to another 
> java package. In this way, this class will belong to another Logger, and 
> this could have a different configuration in log4j. Then, I will remove 
> the traceTerminalIO because this will be configured independently via 
> log4j (With another Appender), and not inside the code.

In that case the Monkey class will need access to both loggers. Regular 
info/warn/error/fatal messages still need to go into benchmark.log.

The traceTerminalIO boolean is there to eliminate spending even those 
CPU cycles for tens for log.trace() calls PER TRANSACTION when we don't 
debug the terminal output, which you would never turn on for an actual 
benchmark run. This is purely for debugging during development of a new 
application, like if we added stored procedure support for MSSQL or DB2.


Regards, Jan

-- 
Jan Wieck
Principle Database Engineer
Amazon Web Services

**Comment by wieck** [comment]
I merged this but reverted the last commit that diverted all log message from the Monkey threads into the terminal trace file. I instead added a secondary log file for the terminal trace. 

Need to adjust the docker build to the new log filenames.

**Pull request merged**
